"""
Stock API routes — self-contained, CSV/JSON-first (no MongoDB required).
Falls back to yfinance for live data if model hasn't been trained yet.
"""
from flask import Blueprint, jsonify, request, current_app
import logging
import os
import json
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)
bp = Blueprint('stocks', __name__)

TICKERS = os.getenv('MONITORED_TICKERS', 'GME,AMC,TSLA,AAPL,MSFT,NVDA').split(',')
# Absolute paths — project root is two levels up from api/routes/
_ROOT       = Path(__file__).resolve().parent.parent.parent
RAW_DIR     = _ROOT / 'data' / 'raw' / 'market'
EVAL_DIR    = _ROOT / 'data' / 'evaluation'
PRED_DIR    = _ROOT / 'data' / 'predictions'
ALERTS_FILE = _ROOT / 'data' / 'alerts.json'

# Per-ticker alert cooldown — only 1 alert per ticker per 15 min
_ALERT_COOLDOWN_MINUTES = 15
_last_alert_time: dict = {}   # ticker -> datetime

# Probability thresholds
ALERT_THRESHOLDS = {'CRITICAL': 0.75, 'HIGH': 0.55, 'MEDIUM': 0.35}


def _maybe_generate_alert(pred: dict) -> None:
    """Write an alert to alerts.json if prediction exceeds threshold and cooldown has passed."""
    prob    = pred.get('manipulation_probability', 0)
    ticker  = pred.get('ticker', 'UNKNOWN')
    risk    = pred.get('risk_level', 'LOW')

    if prob < ALERT_THRESHOLDS['MEDIUM']:
        return   # below any threshold

    now = datetime.now()
    last = _last_alert_time.get(ticker)
    if last and (now - last).total_seconds() < _ALERT_COOLDOWN_MINUTES * 60:
        return   # cooldown active

    _last_alert_time[ticker] = now

    severity_map = {
        'CRITICAL': 'CRITICAL',
        'HIGH':     'HIGH',
        'MEDIUM':   'MEDIUM',
    }
    severity = severity_map.get(risk, 'MEDIUM')
    prob_pct  = round(prob * 100, 1)

    alert = {
        'id':          f"alert_{now.strftime('%Y%m%d%H%M%S%f')}",
        'ticker':      ticker,
        'severity':    severity,
        'message':     f"{ticker}: {prob_pct}% manipulation probability detected ({risk} risk)",
        'probability': round(prob, 4),
        # Accept both key variants produced by RealtimePredictor and rule-based fallback
        'volume_anomaly':  round(float(pred.get('volume_anomaly_prob', pred.get('volume_anomaly', 0))), 4),
        'sentiment_surge': round(float(pred.get('sentiment_surge_prob', pred.get('sentiment_surge', 0))), 4),
        'risk_score':  pred.get('risk_score', 0),
        'timestamp':   now.isoformat(),
    }

    try:
        ALERTS_FILE.parent.mkdir(parents=True, exist_ok=True)
        existing = []
        if ALERTS_FILE.exists():
            with open(ALERTS_FILE) as f:
                existing = json.load(f)
        existing.append(alert)
        with open(ALERTS_FILE, 'w') as f:
            json.dump(existing[-500:], f, indent=2, default=str)
        logger.info(f"Alert generated: {ticker} @ {prob_pct}% ({severity})")
    except Exception as e:
        logger.warning(f"Could not save alert: {e}")


def _is_us_market_open() -> bool:
    """Return True if NYSE is currently in its regular trading session (Mon-Fri 9:30-16:00 ET)."""
    try:
        import zoneinfo
        ny_tz = zoneinfo.ZoneInfo('America/New_York')
    except ImportError:
        from datetime import timezone
        ny_tz = timezone(timedelta(hours=-5))
    now_ny = datetime.now(ny_tz)
    if now_ny.weekday() >= 5:          # Sat=5, Sun=6
        return False
    market_open  = now_ny.replace(hour=9,  minute=30, second=0, microsecond=0)
    market_close = now_ny.replace(hour=16, minute=0,  second=0, microsecond=0)
    return market_open <= now_ny <= market_close


def _fetch_live_ohlcv(ticker: str, n: int = 200) -> list:
    """Fetch live OHLCV from yfinance — always 1-minute bars."""
    try:
        import yfinance as yf
        # 1-min bars: max history is 7 days from yfinance.
        # Use '2d' so we always have data even on partial trading days / pre-market.
        df = yf.download(ticker, period='2d', interval='1m', progress=False, auto_adjust=True)

        if df.empty:
            return []
        df = df.reset_index()
        # Flatten MultiIndex columns if present
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
        
        # Remove duplicate columns generated by new yfinance output structures
        df = df.loc[:, ~df.columns.duplicated(keep='first')]
        
        ts_col = 'Datetime' if 'Datetime' in df.columns else 'Date'
        df = df.rename(columns={ts_col: 'timestamp'})
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce', utc=True)
        df = df.dropna(subset=['timestamp']).sort_values('timestamp').tail(n)
        
        # Ensure Close and Volume are correct types
        df['Close'] = df['Close'].astype(float)
        df['Volume'] = df['Volume'].astype(float)
        
        df['Returns_1h'] = df['Close'].pct_change(fill_method=None).fillna(0)
        # Compute RSI
        delta = df['Close'].diff()
        gain = delta.clip(lower=0).rolling(14, min_periods=1).mean()
        loss = (-delta).clip(lower=0).rolling(14, min_periods=1).mean()
        df['RSI'] = 100 - (100 / (1 + gain / (loss + 1e-9)))
        # Compute MACD
        ema12 = df['Close'].ewm(span=12, adjust=False).mean()
        ema26 = df['Close'].ewm(span=26, adjust=False).mean()
        df['MACD'] = ema12 - ema26
        # Volume Z-score
        vol_mean = df['Volume'].rolling(20, min_periods=1).mean()
        vol_std  = df['Volume'].rolling(20, min_periods=1).std().fillna(1)
        df['Abnormal_Volume_Zscore'] = (df['Volume'] - vol_mean) / (vol_std + 1e-9)
        # Sanitize: fill NaN/inf introduced by rolling windows before serialization
        df = df.fillna(0)
        df = df.replace([float('inf'), float('-inf')], 0)
        logger.info(f'yfinance live chart: {len(df)} candles for {ticker}')
        return df.to_dict(orient='records')
    except Exception as e:
        logger.warning(f'yfinance chart fetch failed for {ticker}: {e}')
        return []


def _load_raw_csv(ticker: str, n: int = 120) -> list:
    """Load last n rows from raw market CSV (fallback when yfinance is unavailable)."""
    path = RAW_DIR / f'{ticker}_market.csv'
    if not path.exists():
        return []
    try:
        df = pd.read_csv(path)
        ts_col = next((c for c in ['timestamp', 'Datetime', 'Date'] if c in df.columns), df.columns[0])
        df = df.rename(columns={ts_col: 'timestamp'})
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        df = df.dropna(subset=['timestamp']).sort_values('timestamp').tail(n)
        df['Returns_1h'] = df['Close'].pct_change().fillna(0)
        return df.to_dict(orient='records')
    except Exception as e:
        logger.error(f'Error loading {ticker}: {e}')
        return []


import time
_PREDICTION_CACHE = {}

def _run_live_prediction(ticker: str) -> dict:
    """Run a quick prediction using the global RealtimePredictor from app.py."""
    now = time.time()
    if ticker in _PREDICTION_CACHE and (now - _PREDICTION_CACHE[ticker]['time']) < 30:
        return _PREDICTION_CACHE[ticker]['data']
        
    try:
        from flask import current_app
        predictor = current_app.config.get('PREDICTOR')
        
        if not predictor:
            logger.warning("Global PREDICTOR not loaded in app context.")
            return {}
            
        pred = predictor.predict(ticker)
        if not pred or 'manipulation_probability' not in pred:
            return {}
            
        market_open = _is_us_market_open()
        
        # Fetch high-speed live price so dashboard grid isn't 0.00
        latest_price = 0.0
        try:
            import yfinance as yf
            tick = yf.Ticker(ticker)
            latest_price = round(float(tick.fast_info['lastPrice']), 4)
        except Exception:
            pass

        # Format mapping from RealtimePredictor to API format
        result = {
            'manipulation_probability': round(float(pred.get('manipulation_probability', 0)), 4),
            'volume_anomaly':           round(float(pred.get('volume_anomaly_prob', 0)),  4),
            'sentiment_surge':          round(float(pred.get('sentiment_surge_prob', 0)), 4),
            'lead_lag_score':           round(float(pred.get('lead_lag_score', 0)), 4),
            'risk_level':               pred.get('risk_level', 'UNKNOWN').upper(),
            'risk_score':               int(pred.get('risk_score', 0)),
            # Confidence fields (from MC Dropout)
            'confidence_score':         round(float(pred.get('confidence_score',    pred.get('manipulation_probability', 0))), 4),
            'confidence_level':         pred.get('confidence_level', 'Unknown'),
            'uncertainty':              round(float(pred.get('uncertainty', 0.0)), 4),
            'confidence_interval':      pred.get('confidence_interval', [0, 0]),
            'latest_price':             latest_price,
            'market_open':              market_open,
            'timestamp':                datetime.now().isoformat(),
        }
        _PREDICTION_CACHE[ticker] = {'time': time.time(), 'data': result}
        return result
    except Exception as e:
        logger.warning(f'Live prediction failed for {ticker}: {e}')
        return {}


# ── Routes ─────────────────────────────────────────────────────────────────

@bp.route('/tickers', methods=['GET'])
def list_tickers():
    """GET /api/tickers — list all monitored tickers with quick status. Auto-generates alerts."""
    result = []
    for ticker in TICKERS:
        t = ticker.strip()
        entry = {'ticker': t, 'status': 'active'}
        pred = _run_live_prediction(t)
        if pred:
            pred['ticker'] = t
            entry.update({
                'manipulation_probability': pred.get('manipulation_probability', 0),
                'risk_level':               pred.get('risk_level', 'UNKNOWN'),
                'latest_price':             pred.get('latest_price'),
            })
            _maybe_generate_alert(pred)  # auto-write alert if above threshold
        result.append(entry)
    return jsonify({'tickers': result, 'count': len(result),
                    'timestamp': datetime.now().isoformat()})


@bp.route('/ticker/<string:symbol>/status', methods=['GET'])
def ticker_status(symbol):
    """GET /api/ticker/<sym>/status — current live metrics and prediction for one ticker."""
    symbol = symbol.upper().strip()
    pred   = _run_live_prediction(symbol)

    # Use live yfinance data (has RSI/MACD/Vol-Z computed) → fall back to raw CSV
    rows = _fetch_live_ohlcv(symbol, n=200) or _load_raw_csv(symbol, n=200)

    if not rows and not pred:
        return jsonify({'error': f'No data available for {symbol}'}), 404

    latest = rows[-1] if rows else {}
    return jsonify({
        'ticker':    symbol,
        'timestamp': datetime.now().isoformat(),
        'market': {
            'latest_price': round(float(latest.get('Close') or latest.get('close') or 0), 4),
            'volume':       int(latest.get('Volume') or latest.get('volume') or 0),
            'returns_1h':   round(float(latest.get('Returns_1h') or latest.get('returns_1h') or 0), 6),
            'rsi':          round(float(latest.get('RSI') or latest.get('rsi') or 50), 2),
            'macd':         round(float(latest.get('MACD') or latest.get('macd') or 0), 6),
            'abnormal_vol': round(float(latest.get('Abnormal_Volume_Zscore') or latest.get('vol_z') or 0), 4),
        },
        'prediction': pred,
    })


@bp.route('/ticker/<string:symbol>/chart', methods=['GET'])
def ticker_chart(symbol):
    """GET /api/ticker/<sym>/chart — live candles from yfinance, fallback to CSV."""
    symbol = symbol.upper().strip()
    n      = request.args.get('n', 100, type=int)
    # Try live data first, fall back to stored CSV
    rows = _fetch_live_ohlcv(symbol, n=n) or _load_raw_csv(symbol, n=n)
    if not rows:
        return jsonify({'error': f'No chart data for {symbol}'}), 404

    def _safe(val, default=0, decimals=4):
        """Convert to float safely, replacing NaN/inf with default."""
        try:
            f = float(val)
            return default if (f != f or f == float('inf') or f == float('-inf')) else round(f, decimals)
        except (TypeError, ValueError):
            return default

    def _fmt(row):
        ts = row.get('timestamp')
        return {
            'timestamp': ts.isoformat() if hasattr(ts, 'isoformat') else str(ts),
            'open':   _safe(row.get('Open'),   decimals=4),
            'high':   _safe(row.get('High'),   decimals=4),
            'low':    _safe(row.get('Low'),    decimals=4),
            'close':  _safe(row.get('Close'),  decimals=4),
            'volume': int(row.get('Volume') or 0),
            'rsi':    _safe(row.get('RSI',   50), default=50, decimals=2),
            'macd':   _safe(row.get('MACD',   0), decimals=6),
            'vol_z':  _safe(row.get('Abnormal_Volume_Zscore', 0), decimals=4),
        }

    return jsonify({
        'ticker': symbol,
        'candles': [_fmt(r) for r in rows],
        'count':   len(rows),
    })
